baseURL: "https://loyayz.com/"
title: loyayz
theme: PaperModx
paginate: 10

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
hasCJKLanguage: true
defaultContentLanguage: zh
timeZone: "Asia/Shanghai"

buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-E7Y0X8JSJJ

minify:
    disableXML: true
    # minifyOutput: true

languages:
    zh:
        languageName: "中文"
        weight: 1
        taxonomies:
            category: categories
            tag: tags

menu:
    main:
        - name: 编程点滴
          url: coding/
          weight: 1
        - name: 建站笔记
          url: website/
          weight: 2
        - name: 搜索
          url: search/
          weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    mainSections:
        - coding
        - website
    env: dev
    title: "loyayz's blog"
    description: "loyayz's blog - https://loyayz.com"
    images: ["papermod-cover.png"]
    keywords: [loyayz,ideaworlds,simpleframework]
    DateFormat: "2006-01-02"
    ShowReadingTime: true
    ShowShareButtons: false
    ShowCodeCopyButtons: true
    ShowFullTextinRSS: false
    defaultTheme: auto
    disableThemeToggle: false
    disableSpecial1stPost: true
    disableScrollToTop: false
    disableAnchoredHeadings: false
    hideMeta: false
    hideSummary: false
    showtoc: true
    tocopen: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowWordCount: true
    ShowRssButtonInSectionTermList: false
    comments: false
    hideFooter: false
    profileMode:
        enabled: true
    socialIcons:
        - name: github
          url: "https://github.com/loyayz"
        - name: email
          url: "mailto:loyayz@foxmail.com"
        - name: RsS
          url: "index.xml"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    #assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    fuseOpts:
        isCaseSensitive: false
        includeMatches: true
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
    randomImgOpt:
        enable: true
        defaultTopics: "wallpapers,star,nature,interiors"

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        codeFences: true
        guessSyntax: true
        lineNos: true
        style: monokai

privacy:
    disqus:
        disable: true
    googleAnalytics:
        disable: false
    instagram:
        disable: true
    twitter:
        disable: true
    vimeo:
        disable: true
    youtube:
        disable: true
